
[functions.crear-enlace-twitch]
enabled = true
verify_jwt = true
import_map = "./functions/crear-enlace-twitch/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crear-enlace-twitch/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crear-enlace-twitch/*.html" ]

[functions.google-api-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/google-api-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/google-api-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/google-api-proxy/*.html" ]

[functions.get-orcid-works]
enabled = true
verify_jwt = true
import_map = "./functions/get-orcid-works/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-orcid-works/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-orcid-works/*.html" ]

[functions.verificar-orcid-code]
enabled = true
verify_jwt = true
import_map = "./functions/verificar-orcid-code/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verificar-orcid-code/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verificar-orcid-code/*.html" ]

[functions.create-zenodo-doi]
enabled = true
verify_jwt = true
import_map = "./functions/create-zenodo-doi/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-zenodo-doi/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-zenodo-doi/*.html" ]

[functions.bsky-auth]
enabled = true
verify_jwt = true
import_map = "./functions/bsky-auth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bsky-auth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bsky-auth/*.html" ]

[functions.bsky-get-community-feed]
enabled = true
verify_jwt = true
import_map = "./functions/bsky-get-community-feed/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bsky-get-community-feed/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bsky-get-community-feed/*.html" ]

[functions.update-community-feed]
enabled = true
verify_jwt = true
import_map = "./functions/update-community-feed/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-community-feed/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-community-feed/*.html" ]

[functions.bsky-like-post]
enabled = true
verify_jwt = true
import_map = "./functions/bsky-like-post/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bsky-like-post/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bsky-like-post/*.html" ]

[functions.bsky-create-reply]
enabled = true
verify_jwt = true
import_map = "./functions/bsky-create-reply/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bsky-create-reply/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bsky-create-reply/*.html" ]

[functions.bsky-create-post]
enabled = true
verify_jwt = true
import_map = "./functions/bsky-create-post/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bsky-create-post/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bsky-create-post/*.html" ]

[functions.bsky-get-post-thread]
enabled = true
verify_jwt = true
import_map = "./functions/bsky-get-post-thread/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bsky-get-post-thread/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bsky-get-post-thread/*.html" ]

[functions.bsky-create-anchor-post]
enabled = true
verify_jwt = true
import_map = "./functions/bsky-create-anchor-post/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bsky-create-anchor-post/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bsky-create-anchor-post/*.html" ]

[functions.update-viewer-count]
enabled = true
verify_jwt = true
import_map = "./functions/update-viewer-count/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-viewer-count/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-viewer-count/*.html" ]

[functions.bot-create-post]
enabled = true
verify_jwt = true
import_map = "./functions/bot-create-post/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bot-create-post/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bot-create-post/*.html" ]

[functions.zoom-signature]
enabled = true
verify_jwt = true
import_map = "./functions/zoom-signature/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/zoom-signature/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/zoom-signature/*.html" ]
