
[functions.crear-enlace-twitch]
enabled = true
verify_jwt = true
import_map = "./functions/crear-enlace-twitch/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crear-enlace-twitch/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crear-enlace-twitch/*.html" ]

[functions.google-api-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/google-api-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/google-api-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/google-api-proxy/*.html" ]

[functions.get-orcid-works]
enabled = true
verify_jwt = true
import_map = "./functions/get-orcid-works/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-orcid-works/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-orcid-works/*.html" ]

[functions.verificar-orcid-code]
enabled = true
verify_jwt = true
import_map = "./functions/verificar-orcid-code/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verificar-orcid-code/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verificar-orcid-code/*.html" ]

[functions.create-zenodo-doi]
enabled = true
verify_jwt = true
import_map = "./functions/create-zenodo-doi/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-zenodo-doi/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-zenodo-doi/*.html" ]
